import{a as p,S as m,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const y="51801450-0916bf82cabb3a5bfe1ad6ca6",g="https://pixabay.com/api/";async function h(o){try{const e=await p.get(g,{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}});return!e.data||!e.data.hits?{hits:[]}:e.data}catch(e){throw console.error("Помилка при отриманні зображень:",e),e}}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),L=new m(".gallery a",{captionsData:"alt",captionDelay:250});function b(){c.innerHTML=""}function w(o){const e=o.map(({largeImageURL:n,webformatURL:i,tags:t,likes:r,views:a,comments:d,downloads:f})=>`
        <a class="gallery__link" href="${n}">
        <img class="gallery__image" src="${i}" alt="${t}" loading="lazy" />
        <div class="info">
        <p>Likes: ${r}</p>
        <p>Views: ${a}</p>
        <p>Comments: ${d}</p>
        <p>Downloads: ${f}</p>
  </div>
</a>
      `).join("");c.insertAdjacentHTML("beforeend",e),L.refresh()}function S(){l.classList.remove("hidden")}function E(){l.classList.add("hidden")}const u=document.querySelector(".form"),q=u.querySelector('input[name="search-text"]');async function v(o){b(),S();try{const e=await h(o);if(e.hits.length===0){s.warning({title:"Sorry",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}w(e.hits)}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{E()}}u.addEventListener("submit",o=>{o.preventDefault();const e=q.value.trim();if(!e){s.warning({title:"Oops",message:"Please enter a search term!",position:"topRight"});return}v(e)});
//# sourceMappingURL=index.js.map
